[package]
name = "texthooker_websocket_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
env_logger = "0.11.6"
futures-util = "0.3.28"
log = "0.4.20"
tokio = { version = "1.32.0", features = ["full"] }
tokio-tungstenite = "0.26.1"
